---
- name: Install, enable and start Docker
  hosts: provisioner_instance
  become: yes
  remote_user: ec2-user
  tasks:
  - name: Pull Confluence Docker image
    shell:
      cmd: sudo docker pull atlassian/confluence-server:7.13.3-adoptopenjdk11
  - name: Tag Confluence Docker image
    shell:
      cmd: sudo docker tag atlassian/confluence-server:7.13.3-adoptopenjdk11 367831582769.dkr.ecr.eu-central-1.amazonaws.com/confluence_image_repo:7.13.3-adoptopenjdk11
  - name: Login to ECR via Docker and AWS CLI, upload image
    environment:
      AWS_ACCESS_KEY_ID: AKIAVLJDYRAYS5LVLK7M
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: eu-central-1
    shell:
      cmd: aws ecr get-login-password | docker login --username AWS --password-stdin 367831582769.dkr.ecr.eu-central-1.amazonaws.com; sudo docker push 367831582769.dkr.ecr.eu-central-1.amazonaws.com/confluence_image_repo:7.13.3-adoptopenjdk11
